routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/profile', 'ProfileController@edit')->name('profile');
    Route::put('/profile', 'ProfileController@update')->name('profile.update');
});

Route::group(
    ['middleware' => ['auth', 'role:administrator|admin|keuangan'], 'namespace' => 'Admin'],
    function () {
        Route::get('/', 'HomeController@index')->name('index');

        Route::resource('users', 'UserController');
        Route::resource('jabatans', 'JabatanController');

        Route::get('products/report', 'ProductController@report')->name('products.report');
        Route::resource('products', 'ProductController');

        Route::get('orders/report', 'OrderController@report')->name('orders.report');
        Route::get('/orders/export/{order}', 'OrderController@export')->name('orders.export');
        Route::resource('orders', 'OrderController')->only(['show', 'index']);
        Route::patch('/orders/{order}/change-status', 'OrderController@changeStatus')->name('orders.change-status');
    }
);

Route::group(
    ['middleware' => ['auth', 'role:user'], 'prefix' => 'app', 'as' => 'app.'],
    function () {
        Route::get('/', 'HomeController@index')->name('index');
        Route::get('product', 'ProductController@index')->name('product');
        Route::post('product/add-to-cart', 'ProductController@addToCart')->name('product.add-to-cart');
        Route::get('cart', 'ProductController@cart')->name('cart');
        Route::get('cart/remove-from-cart/{cart_id}', 'ProductController@removeFromCart')->name('cart.remove-from-cart');
        Route::post('cart/update-cart/{cart_id}', 'ProductController@updateCart')->name('cart.update-cart');

        Route::resource('orders', 'OrderController')->only(['show', 'index', 'store']);
        Route::get('/orders/export/{order}', 'OrderController@export')->name('orders.export');
    }
);

app/Models/Order.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['status'];
    protected $appends = ['label_status', 'tanggal_pesan'];

    public function generateCode()
    {
        $monthyear = date('ymd');
        $currentCode = 'INV/' . $monthyear . '/KPR/DMC/';

        $last = self::whereYear('created_at', date('Y'))->latest()->first();

        if (is_null($last)) {
            $code = $currentCode . '00001';
        } else {
            $lastNum = (int) substr($last->invoice_code, -5);
            $code = $currentCode .  str_pad($lastNum + 1, 5, '0', STR_PAD_LEFT);
        }

        return $code;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function details()
    {
        return $this->hasMany(OrderDetail::class);
    }

    public function getLabelStatusAttribute()
    {
        switch ($this->status) {
            case 0:
                return '<span class="badge badge-warning">Menunggu persetujuan</span>';
            case 1:
                return '<span class="badge badge-info">Menyiapkan pesanan</span>';
            case 2:
                return '<span class="badge badge-light">Pesanan siap diambil</span>';
            case 3:
                return '<span class="badge badge-success">Selesai</span>';
            case 4:
                return '<span class="badge badge-dark">Dibatalkan</span>';
            case 5:
                return '<span class="badge badge-danger">Ditolak</span>';
        }
    }

    public function getTextStatusAttribute()
    {
        switch ($this->status) {
            case 0:
                return 'Menunggu persetujuan';
            case 1:
                return 'Menyiapkan pesanan';
            case 2:
                return 'Pesanan siap diambil';
            case 3:
                return 'Selesai';
            case 4:
                return 'Dibatalkan';
            case 5:
                return 'Ditolak';
        }
    }

    public function getTanggalPesanAttribute()
    {
        return $this->created_at->isoFormat('dddd, D MMMM Y HH:mm');
    }

    public function getTotalHargaAttribute()
    {
        return "Rp. " . number_format($this->details->sum('sub_total_price'), 0, ',', '.');
    }

    public function isWaiting()
    {
        return $this->status == 0;
    }

    public function isProcessing()
    {
        return $this->status == 1;
    }

    public function isReady()
    {
        return $this->status == 2;
    }

    public function isFinished()
    {
        return $this->status == 3;
    }

    public function isCanceled()
    {
        return $this->status == 4;
    }

    public function isRejected()
    {
        return $this->status == 5;
    }
}

app/Models/OrderDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OrderDetail extends Model
{
    protected $fillable = [
        'product_id', 'product_name', 'quantity', 'price', 'sub_total_price', 'order_id'
    ];

    protected $guarderd = [];

    public function getHargaAttribute()
    {
        return "Rp. " . number_format($this->price, 0, ',', '.');
    }

    public function getSubTotalHargaAttribute()
    {
        return "Rp. " . number_format($this->sub_total_price, 0, ',', '.');
    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}

app/User.php
<?php

namespace App;

use App\Models\Jabatan;
use App\Models\Order;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Storage;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getPhotoUrlAttribute()
    {
        if ($this->photo) {
            return Storage::url($this->photo);
        }
        return Null;
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function jabatan()
    {
        return $this->belongsTo(Jabatan::class);
    }

    public function getLimitRemainingAdminAttribute()
    {
        $usage = $this->orders()
            ->whereBetween('status', [1, 3])
            ->where('created_at', ">=", now()->startOfMonth())
            ->withSum('details', 'sub_total_price')
            ->get()
            ->sum('details_sum_sub_total_price');
        return $this->limit_balance - $usage;
    }

    public function getLimitRemainingUserAttribute()
    {
        $usage = $this->orders()
            ->where('created_at', ">=", now()->startOfMonth())
            ->where('status', '<=', 4)
            ->withSum('details', 'sub_total_price')
            ->get()
            ->sum('details_sum_sub_total_price');
        return $this->limit_balance - $usage;
    }

    public function isUser()
    {
        return $this->role == 'user';
    }

    public function isAdmin()
    {
        return $this->role == 'admin';
    }

    public function isAdministrator()
    {
        return $this->role == 'administrator';
    }

    public function isKeuangan()
    {
        return $this->role == 'keuangan';
    }
}

resources/views/app/cart.blade.php
@extends('layouts.app')
@section('css')
<style type="text/css">
    .card-recent {
      height: 250px;
    }
</style>
@endsection
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <div class="d-flex justify-content-between items-center w-full" style="width: 100%">
                    <h1>Keranjang Belanja</h1>
                    <h1>
                        Sisa Limit: Rp. {{ number_format(request()->user()->limit_remaining_user, 0, ',', '.') }}
                    </h1>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <table class="table table-bordered table-hover shopping-cart-wrap">
                                    <thead class="text-muted">
                                    <tr>
                                      <th scope="col">Produk</th>
                                      <th scope="col" width="150">Jumlah</th>
                                      <th scope="col" width="180">Total Harga</th>
                                      <th scope="col" width="200" class="text-right">Aksi</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @php
                                        $total = 0;
                                        @endphp
                                        @foreach($carts as $cart)
                                        <form method="POST" action="{{ route('app.cart.update-cart', $cart->id) }}">
                                            @csrf
                                          <tr>
                                            <td>
                                              <figure class="media mt-2">
                                                <div class="img-wrap"><img src="{{ $cart->product->photo_url }}" style="max-width: 100px; padding-right:1rem"></div>
                                                <figcaption class="media-body">
                                                  <h6 class="title text-truncate">{{ $cart->product->name }}</h6>
                                                  <div class="param param-inline small">
                                                    <dt>Harga : </dt>
                                                    <dd>{{ $cart->product->price_rupiah }}</dd>
                                                  </div>
                                                </figcaption>
                                              </figure>
                                            </td>
                                            <td>
                                              <input type="number" value="{{ $cart->quantity }}" name="quantity" class="form-control">
                                            </td>
                                            <td>
                                              <div class="price-wrap" align="right">
                                                <var class="price">{{ $cart->getSubTotal($cart->product->price) }}</var>
                                              </div>
                                            </td>
                                            <td class="text-right">
                                              <button type="submit" class="btn btn-outline-warning">Update</button>
                                              <a href="{{ route('app.cart.remove-from-cart', $cart->id) }}" class="btn btn-outline-danger">Hapus</a>
                                            </td>
                                          </tr>
                                        </form>
                                        @php
                                        $total += $cart->quantity * $cart->product->price;
                                        @endphp
                                        @endforeach
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                        <th class="text-right" colspan="3">Total</th>
                                        <td class="text-right" colspan="2">
                                            <div class="price-wrap">
                                            <span class="price"><b>Rp. {{ number_format($total, 0, ',', '.') }}</b></span>
                                            </div>
                                        </td>
                                        </tr>
                                    </tfoot>
                                </table>
                                @if(count($carts) > 0)
                                <div class="d-flex justify-content-end">
                                    <form method="POST" action="{{ route('app.orders.store') }}">
                                        @csrf
                                        <input type="hidden" value="{{ $total }}" name="total">
                                        <button class="btn btn-primary">
                                            <i class="fa fa-chevron-right"></i> Ajukan Pesanan
                                        </button>
                                    </form>
                                </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/app/index.blade.php
@extends('layouts.app')
@section('css')
<style type="text/css">
    .card-recent {
      height: 250px;
    }
</style>
@endsection
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Koperasi Karyawan</h1>
            </div>

            <div class="section-body">

                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                      <div class="card card-statistic-1">
                        <div class="card-icon bg-primary">
                          <i class="far fa-user"></i>
                        </div>
                        <div class="card-wrap">
                          <div class="card-header">
                            <h4>Limit Bulanan</h4>
                          </div>
                          <div class="card-body">
                            Rp. {{ number_format(request()->user()->limit_balance, 0, ',', '.') }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                      <div class="card card-statistic-1">
                        <div class="card-icon bg-danger">
                          <i class="far fa-newspaper"></i>
                        </div>
                        <div class="card-wrap">
                          <div class="card-header">
                            <h4>Sisa Limit</h4>
                          </div>
                          <div class="card-body">
                            Rp. {{ number_format(request()->user()->limit_remaining_user, 0, ',', '.') }}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                <div class="row">
                    <div class="col-md-12">
                        <div style="margin-top: 5vh">
                            <center>
                                <img src="{{ asset('logo.png') }}" style="width:300px;margin-bottom:35px">
                                <hr>
                                <p style="font-size: 14pt">
                                    PT. Dhanarmas Concern adalah salah satu perusahaan tekstil yang berdiri sejak tahun 1964 di Bandung.
                                    Orientasi produk kami yang sebagian besar adalah ekspor, menjadikan kami terus mengembangkan diri baik dari kualitas produk yang dihasilkan
                                    maupun sumber daya manusia yang menjadi motor penggerak.
                                </p>
                                <p>Jl. Moh. Toha Jl. Cisirung No.KM 6.8, Pasawahan, Kec. Dayeuhkolot, Kabupaten Bandung, Jawa Barat 40256</p>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/app/orders.blade.php
@extends('layouts.app')
@section('css')
<style type="text/css">
    .card-recent {
      height: 250px;
    }
</style>
@endsection
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Daftar Pesanan</h1>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">

                                  <div class="table-responsive">
                                    <table class="table table-striped">
                                      <tr>
                                        <th>No</th>
                                        <th>Kode Pesanan</th>
                                        <th>Total Harga</th>
                                        <th>Status</th>
                                        <th>Tanggal Pengajuan</th>
                                        <th>#</th>
                                      </tr>
                                      @forelse ($orders as $item)
                                      <tr>
                                          <td>{{ (($orders->currentPage()-1) * $orders->perPage()) + $loop->iteration }}</td>
                                          <td>{{ $item->invoice_code }}</td>
                                          <td>{{ $item->total_harga }}</td>
                                          <td align="center">{!! $item->label_status !!}</td>
                                          <td>{{ $item->tanggal_pesan }}</td>
                                          <td>
                                              <a href="{{ route('app.orders.show', $item) }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Lihat Pesanan"> <span class="fa fa-eye"></span></a>
                                          </td>
                                      </tr>
                                      @empty
                                      <tr>
                                          <td colspan="7" align="center">
                                              <div class="empty-state" data-height="400" style="height: 400px;">
                                                  <div class="empty-state-icon">
                                                    <i class="fas fa-question"></i>
                                                  </div>
                                                  <h2>Data Tidak Ditemukan</h2>
                                                  <p class="lead">
                                                    Maaf kami tidak dapat menemukan data.
                                                  </p>
                                              </div>
                                          </td>
                                      </tr>
                                      @endforelse
                                    </table>
                                  </div>
                                  <div class="float-right">
                                    {{ $orders->links() }}
                                  </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/app/product.blade.php
@extends('layouts.app')
@section('css')
<style type="text/css">
    .card-recent {
      height: 250px;
    }
</style>
@endsection
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Daftar Produk</h1>
            </div>

            <div class="section-body">
                <div class="row">
                    @foreach ($products as $index => $product)
                    <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                        <article class="article article-style-b">
                           <div class="article-header">
                              <div class="article-image" data-background="{{ $product->photo_url }}">
                              </div>
                           </div>
                           <div class="article-details">
                              <div class="article-title text-black">
                                <a href="#"  onclick="showDetail({{ $index }})">
                                    <h6>{{ $product->name }}</h6>
                                </a>
                              </div>
                              <div class="d-flex justify-content-between">
                                <strong class="text-info">{{ $product->price_rupiah }}</strong> <br>
                                <span>Stock ({{ $product->stock }})</span>
                              </div>
                              <div class="mt-2">
                                  <button class="btn btn-sm btn-outline-info" onclick="showDetail({{ $index }})">
                                      Pesan <i class="fas fa-chevron-right"></i>
                                  </button>
                              </div>
                           </div>
                        </article>
                     </div>
                    @endforeach
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="float-right">
                            {{ $products->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" id="modalDetail">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <form action="{{ route('app.product.add-to-cart') }}" method="POST">
                @csrf
                <input type="hidden" name="product_id" id="product-id">
                <div class="modal-header">
                    <h5 class="modal-title" id="product-name"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <img src="" alt="" srcset="" id="product-image" class="img-fluid">
                    <h6 class="text-info" id="product-price"></h6>
                </div>
                <div class="modal-footer bg-whitesmoke br">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-primary">Tambahkan ke keranjang</button>
                </div>
            </form>
          </div>
        </div>
    </div>

@endsection

@section('js')
    <script>
        var products = @json($products)

        function showDetail(index) {
            const product = products.data[index]

            $('#modalDetail').modal('show')
            $('#product-name').html(product.name)
            $('#product-image').attr('src', product.photo_url)
            $('#product-price').html(product.price_rupiah)
            $('#product-id').val(product.id)
        }
    </script>
@endsection

resources/views/app/show-order.blade.php
@extends('layouts.app')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('app.orders.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Detail Pesanan</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="{{ route('app.orders.index') }}">Pesanan</a></div>
          <div class="breadcrumb-item">Detail Pesanan</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                  <h4>Invoice : {{$order->invoice_code }}</h4>
                  <a class="btn btn-primary" href="{{ route('app.orders.export', $order) }}">Download PDF</a>
                </div>
                <div class="card-body">
                  <div class="row mb-2">
                    <div class="col-md-6">
                      <b>Nama Pegawai</b><br>
                      {{ $order->employee_name }}<br>
                    </div>
                    <div class="col-md-3">
                      <b>Total Harga</b><br>
                      {{ $order->total_harga }}
                    </div>
                    <div class="col-md-3">
                      <b>Status Pesanan</b><br>
                      {!! $order->label_status !!}<br><br>
                    </div>
                  </div>
                </div>
            </div>

            <div class="card">
              <div class="card-header">
                <h4>Data Produk</h4>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered">
                    <tr>
                      <th>No</th>
                      <th>Nama Produk</th>
                      <th>Harga</th>
                      <th>Qty</th>
                      <th>Sub Total</th>
                    </tr>
                    @php $no = 1 @endphp
                    @forelse ($order->details as $detail)
                        <tr >
                            <td>{{ $no }}</td>
                            <td>{{ $detail->product_name }}</td>
                            <td>{{ $detail->harga}}</td>
                            <td>{{ $detail->quantity}}</td>
                            <td>{{ $detail->sub_total_harga}}</td>
                        </tr>
                        @php $no++ @endphp
                    @empty
                    <tr>
                        <td colspan="5" align="center">
                            <div class="empty-state" data-height="400" style="height: 400px;">
                                <div class="empty-state-icon">
                                  <i class="fas fa-question"></i>
                                </div>
                                <h2>Data Tidak Ditemukan</h2>
                                <p class="lead">
                                  Maaf kami tidak dapat menemukan data.
                                </p>
                            </div>
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')

@endsection