routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/profile', 'ProfileController@edit')->name('profile');
    Route::put('/profile', 'ProfileController@update')->name('profile.update');
});

Route::group(
    ['middleware' => ['auth', 'role:administrator|admin|keuangan'], 'namespace' => 'Admin'],
    function () {
        Route::get('/', 'HomeController@index')->name('index');

        Route::resource('users', 'UserController');
        Route::resource('jabatans', 'JabatanController');

        Route::get('products/report', 'ProductController@report')->name('products.report');
        Route::resource('products', 'ProductController');

        Route::get('orders/report', 'OrderController@report')->name('orders.report');
        Route::get('/orders/export/{order}', 'OrderController@export')->name('orders.export');
        Route::resource('orders', 'OrderController')->only(['show', 'index']);
        Route::patch('/orders/{order}/change-status', 'OrderController@changeStatus')->name('orders.change-status');
    }
);

Route::group(
    ['middleware' => ['auth', 'role:user'], 'prefix' => 'app', 'as' => 'app.'],
    function () {
        Route::get('/', 'HomeController@index')->name('index');
        Route::get('product', 'ProductController@index')->name('product');
        Route::post('product/add-to-cart', 'ProductController@addToCart')->name('product.add-to-cart');
        Route::get('cart', 'ProductController@cart')->name('cart');
        Route::get('cart/remove-from-cart/{cart_id}', 'ProductController@removeFromCart')->name('cart.remove-from-cart');
        Route::post('cart/update-cart/{cart_id}', 'ProductController@updateCart')->name('cart.update-cart');

        Route::resource('orders', 'OrderController')->only(['show', 'index', 'store']);
        Route::get('/orders/export/{order}', 'OrderController@export')->name('orders.export');
    }
);

app/Models/Order.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['status'];
    protected $appends = ['label_status', 'tanggal_pesan'];

    public function generateCode()
    {
        $monthyear = date('ymd');
        $currentCode = 'INV/' . $monthyear . '/KPR/DMC/';

        $last = self::whereYear('created_at', date('Y'))->latest()->first();

        if (is_null($last)) {
            $code = $currentCode . '00001';
        } else {
            $lastNum = (int) substr($last->invoice_code, -5);
            $code = $currentCode .  str_pad($lastNum + 1, 5, '0', STR_PAD_LEFT);
        }

        return $code;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function details()
    {
        return $this->hasMany(OrderDetail::class);
    }

    public function getLabelStatusAttribute()
    {
        switch ($this->status) {
            case 0:
                return '<span class="badge badge-warning">Menunggu persetujuan</span>';
            case 1:
                return '<span class="badge badge-info">Menyiapkan pesanan</span>';
            case 2:
                return '<span class="badge badge-light">Pesanan siap diambil</span>';
            case 3:
                return '<span class="badge badge-success">Selesai</span>';
            case 4:
                return '<span class="badge badge-dark">Dibatalkan</span>';
            case 5:
                return '<span class="badge badge-danger">Ditolak</span>';
        }
    }

    public function getTextStatusAttribute()
    {
        switch ($this->status) {
            case 0:
                return 'Menunggu persetujuan';
            case 1:
                return 'Menyiapkan pesanan';
            case 2:
                return 'Pesanan siap diambil';
            case 3:
                return 'Selesai';
            case 4:
                return 'Dibatalkan';
            case 5:
                return 'Ditolak';
        }
    }

    public function getTanggalPesanAttribute()
    {
        return $this->created_at->isoFormat('dddd, D MMMM Y HH:mm');
    }

    public function getTotalHargaAttribute()
    {
        return "Rp. " . number_format($this->details->sum('sub_total_price'), 0, ',', '.');
    }

    public function isWaiting()
    {
        return $this->status == 0;
    }

    public function isProcessing()
    {
        return $this->status == 1;
    }

    public function isReady()
    {
        return $this->status == 2;
    }

    public function isFinished()
    {
        return $this->status == 3;
    }

    public function isCanceled()
    {
        return $this->status == 4;
    }

    public function isRejected()
    {
        return $this->status == 5;
    }
}

app/Models/OrderDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OrderDetail extends Model
{
    protected $fillable = [
        'product_id', 'product_name', 'quantity', 'price', 'sub_total_price', 'order_id'
    ];

    protected $guarderd = [];

    public function getHargaAttribute()
    {
        return "Rp. " . number_format($this->price, 0, ',', '.');
    }

    public function getSubTotalHargaAttribute()
    {
        return "Rp. " . number_format($this->sub_total_price, 0, ',', '.');
    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}

app/User.php
<?php

namespace App;

use App\Models\Jabatan;
use App\Models\Order;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Storage;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getPhotoUrlAttribute()
    {
        if ($this->photo) {
            return Storage::url($this->photo);
        }
        return Null;
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function jabatan()
    {
        return $this->belongsTo(Jabatan::class);
    }

    public function getLimitRemainingAdminAttribute()
    {
        $usage = $this->orders()
            ->whereBetween('status', [1, 3])
            ->where('created_at', ">=", now()->startOfMonth())
            ->withSum('details', 'sub_total_price')
            ->get()
            ->sum('details_sum_sub_total_price');
        return $this->limit_balance - $usage;
    }

    public function getLimitRemainingUserAttribute()
    {
        $usage = $this->orders()
            ->where('created_at', ">=", now()->startOfMonth())
            ->where('status', '<=', 4)
            ->withSum('details', 'sub_total_price')
            ->get()
            ->sum('details_sum_sub_total_price');
        return $this->limit_balance - $usage;
    }

    public function isUser()
    {
        return $this->role == 'user';
    }

    public function isAdmin()
    {
        return $this->role == 'admin';
    }

    public function isAdministrator()
    {
        return $this->role == 'administrator';
    }

    public function isKeuangan()
    {
        return $this->role == 'keuangan';
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\{Order, Product, Production, Customer, ProductVariant};
use App\Exports\{OrderReport, OrderDetailReport};
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Excel;
use PDF;

use App\Mail\InvoiceOrder;
use Illuminate\Support\Facades\Mail;

class OrderController extends Controller
{
    public function index(Request $request)
    {
        $orders = Order::latest()->with('details');

        if ($request->has('search')) {
            $query = '%' . $request->search . '%';
            $orders->where('employee_name', 'LIKE', $query);
        }

        if ($request->daterange) {
            $daterange = explode(" - ", $request->daterange);
            $date_from = Carbon::createFromFormat('d/m/Y', $daterange[0]);
            $date_to = Carbon::createFromFormat('d/m/Y', $daterange[1]);

            $from = $date_from->format('Y-m-d');
            $to = $date_to->format('Y-m-d');
        } else {
            $from = date("Y-m-d", strtotime('-1 months'));
            $to = date("Y-m-d");

            $date_from = Carbon::createFromFormat('Y-m-d', $from);
            $date_to = Carbon::createFromFormat('Y-m-d', $to);
        }

        $orders->whereDate('created_at', '>=', $from)
            ->whereDate('created_at', '<=', $to);

        $orders = $orders->paginate(config('app.per_page'))->withQueryString();

        return view('admin.order.index', compact('orders'));
    }

    public function show(Order $order)
    {
        $order->with('details');
        $products = $order->details->groupBy('product_name');

        return view('admin.order.show', compact('order', 'products'));
    }

    public function toggleStatus(Order $order)
    {
        try {
            \DB::beginTransaction();

            $order->status = 1;
            $order->save();

            $productions = $order->details->map(function ($detail) {
                $detail->sub_total_size = $detail->quantity * $detail->product_size;
                return $detail->only('product_name', 'product_variant_id', 'quantity', 'product_size', 'sub_total_size');
            });
            $totalSize = $productions->sum('sub_total_size');

            $production = new Production;
            $production->code = $production->generateCode();
            $production->type = 'order';
            $production->order_id = $order->id;
            $production->status = 0;
            $production->total_size = $totalSize;
            $production->save();
            $production->details()->createMany($productions->toArray());

            \DB::commit();
        } catch (\Exception $e) {
            \DB::rollback();
            return redirect()->back()->withInput()->with('alert-error', 'Terjadi kesalahan server');
        }

        return redirect()->back()->with('alert-success', 'Berhasil Menambah Data Produksi');
    }

    public function report(Request $request)
    {
        $orders = Order::query();

        if ($request->daterange) {
            $daterange = explode(" - ", $request->daterange);
            $date_from = Carbon::createFromFormat('d/m/Y', $daterange[0]);
            $date_to = Carbon::createFromFormat('d/m/Y', $daterange[1]);

            $from = $date_from->format('Y-m-d');
            $to = $date_to->format('Y-m-d');
        } else {
            $from = date("Y-m-d", strtotime('-1 months'));
            $to = date("Y-m-d");

            $date_from = Carbon::createFromFormat('Y-m-d', $from);
            $date_to = Carbon::createFromFormat('Y-m-d', $to);
        }

        if ($request->has('search')) {
            $query = '%' . $request->search . '%';
            $orders->where('employee_name', 'LIKE', $query);
        }

        $orders = $orders->whereDate('created_at', '>=', $from)
            ->whereDate('created_at', '<=', $to)
            ->get();

        $filename = 'Laporan Pesanan ' . $date_from->isoFormat('D MMMM Y') . ' - ' . $date_to->isoFormat('D MMMM Y');
        return Excel::download(new OrderReport($orders, $filename), $filename . '.xlsx');
    }

    public function changeStatus(Request $request, Order $order)
    {
        $order->status = $request->status;
        $order->load('details');
        if ($request->status == 3 || $request->status == 4) {
            foreach ($order->details as $detail) {
                $product = $detail->product;
                if ($request->status == 3) {
                    $product->stock -= $detail->quantity;
                } elseif ($request->status == 4) {
                    $product->stock += $detail->quantity;
                }
                $product->save();
            }
        }

        $order->save();

        return redirect()->back()->with('alert-success', 'Berhasil mengubah status pesanan');
    }

    public function export(Request $request, Order $order)
    {
        $code = str_replace('/', '-', $order->invoice_code);

        $filename = 'Invoice ' . $code;

        $pdf = PDF::loadView('report.invoice', compact('order'));
        return $pdf->download($filename . '.pdf');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cart;
use App\Models\Order;
use App\Models\OrderDetail;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use PDF;

class OrderController extends Controller
{
    public function index(Request $request)
    {
        $orders = Order::where('user_id', $request->user()->id)
            ->with('details')
            ->latest()
            ->paginate(config('app.per_page'));

        return view('app.orders', compact('orders'));
    }

    public function store(Request $request)
    {
        $user = Auth::user();

        $carts = Cart::where('user_id', $user->id)->with('product')->get();

        if ($request->total > $user->limit_remaining_user) {
            return redirect()->back()->with('alert-error', 'Jumlah pesanan melebihi sisa limit. Sisa Limit: Rp.' . number_format(request()->user()->limit_remaining_user, 0, ',', '.'));
        }

        try {
            DB::beginTransaction();

            $order = new Order;
            $order->user_id = $user->id;
            $order->invoice_code = $order->generateCode();
            $order->employee_name = $user->name;
            $order->employee_phone = $user->phone;
            $order->status = 0;
            $order->save();

            foreach ($carts as $cart) {
                $product = $cart->product;

                $detail = new OrderDetail;
                $detail->order_id = $order->id;
                $detail->product_id = $product->id;
                $detail->product_name = $product->name;
                $detail->price = $product->price;
                $detail->quantity = $cart->quantity;
                $detail->sub_total_price = $detail->price * $detail->quantity;
                $detail->save();

                $cart->delete();
            }

            DB::commit();
            return redirect()->route('app.orders.index')->with('alert-success', 'Berhasil membuat pesanan');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->with('alert-error', 'Terjadi kesalahan, Silahkan ulangi!');
        }
    }

    public function show(Order $order)
    {
        $user = Auth::user();
        if ($order->user_id != $user->id) {
            abort(403);
        }

        return view('app.show-order', compact('order'));
    }

    public function export(Request $request, Order $order)
    {
        $user = Auth::user();
        if ($order->user_id != $user->id) {
            abort(403);
        }

        $code = str_replace('/', '-', $order->invoice_code);

        $filename = 'Invoice ' . $code;

        $pdf = PDF::loadView('report.invoice', compact('order'));
        return $pdf->download($filename . '.pdf');
    }
}

resources/views/admin/order/index.blade.php
@extends('layouts.admin')

@php
    $auth = request()->user();
@endphp

@section('css')
<link rel="stylesheet" href="{{asset('/stisla-2.2.0/dist/assets/modules/bootstrap-daterangepicker/daterangepicker.css')}}">
@endsection
@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Pesanan</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Pesanan</a></div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Daftar Pesanan</h4>
              </div>
              <div class="card-body">
                <div class="float-left d-flex">
                    <button onclick="report()" class="btn btn-info">Laporan Pesanan</button>
                </div>
                <div class="float-right">
                  <form action="" method="GET" >
                    <div class="input-group">
                      @if(request()->daterange)
                        @php
                        $daterange=explode(" - ", request()->daterange);
                        $date_from = \Carbon\Carbon::createFromFormat('d/m/Y', $daterange[0]);
                        $date_to = \Carbon\Carbon::createFromFormat('d/m/Y', $daterange[1]);

                        $from = $date_from->format('d/m/Y');
                        $to = $date_to->format('d/m/Y');
                        @endphp
                        <input type="text" class="form-control daterange-cus mr-2" name="daterange" id="daterange" value="{{ $from }} - {{ $to }}">
                      @else
                      <input type="text" class="form-control daterange-cus mr-2" name="daterange" id="daterange" value="{{ date('d/m/Y', strtotime('-1 months'))}} - {{date("d/m/Y")}}">
                      @endif
                      <input type="text" class="form-control" name="search" placeholder="Search" id="search" value="{{ request()->search }}">
                      <div class="input-group-append">
                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                      </div>
                    </div>
                  </form>
                </div>

                <div class="clearfix mb-3"></div>

                <div class="table-responsive">
                  <table class="table table-striped">
                    <tr>
                      <th>No</th>
                      <th>Kode Pesanan</th>
                      <th>Nama Pemesan</th>
                      <th>Total Harga</th>
                      <th>Status</th>
                      <th>Tanggal Pengajuan</th>
                      <th>#</th>
                    </tr>
                    @forelse ($orders as $item)
                    <tr>
                        <td>{{ (($orders->currentPage()-1) * $orders->perPage()) + $loop->iteration }}</td>
                        <td>{{ $item->invoice_code }}</td>
                        <td>{{ $item->employee_name }}</td>
                        <td>{{ $item->total_harga }}</td>
                        <td align="center">{!! $item->label_status !!}</td>
                        <td>{{ $item->tanggal_pesan }}</td>
                        <td>
                            <a href="{{ route('orders.show', $item) }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Lihat Pesanan"> <span class="fa fa-eye"></span></a>

                            @if(!$item->isFinished() && !$item->isCanceled() && !$item->isRejected())
                                {{-- Batalkan Pesanan --}}
                                {{-- <span class="btn btn-sm btn-warning btn-status" href="{{ route('orders.change-status', $item) }}" data-toggle="tooltip" data-placement="top" data-action="4" data-title="Batalkan Pesanan"> <span class="fa fa-undo"></span></span> --}}

                                @if($item->isWaiting() && $auth->isAdministrator())
                                {{-- Siapkan Pesanan --}}
                                <span class="btn btn-sm btn-primary btn-status" href="{{ route('orders.change-status', $item) }}" data-total="{{ $item->total_harga }}" data-limit="{{ number_format($item->user->limit_remaining_admin, 0, ',', '.') }}" data-toggle="tooltip" data-placement="top" data-action="1" data-title="Terima Pesanan"> <span class="fa fa-check"></span></span>
                                @endif

                                @if($item->isProcessing() && ($auth->isAdmin() || $auth->isAdministrator()))
                                {{-- Tandai Siap Diambil --}}
                                <span class="btn btn-sm btn-primary btn-status" href="{{ route('orders.change-status', $item) }}" data-toggle="tooltip" data-placement="top" data-action="2" data-title="Tandai Siap Diambil"> <span class="fa fa-box"></span></span>
                                @endif


                                @if($item->isReady() && ($auth->isAdmin() || $auth->isAdministrator()))
                                {{-- Tandai Selesai --}}
                                <span class="btn btn-sm btn-primary btn-status" href="{{ route('orders.change-status', $item) }}" data-toggle="tooltip" data-placement="top" data-action="3" data-title="Tandai Selesai"> <span class="fa fa-hands"></span></span>
                                @endif

                                @if($item->isWaiting() && $auth->isAdministrator())
                                {{-- Tolak Pesanan --}}
                                    <span class="btn btn-sm btn-danger btn-status" href="{{ route('orders.change-status', $item) }}" data-toggle="tooltip" data-placement="top" data-action="5" data-title="Tolak Pesanan"> <span class="fa fa-times"></span></span>
                                @endif
                            @endif
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" align="center">
                            <div class="empty-state" data-height="400" style="height: 400px;">
                                <div class="empty-state-icon">
                                  <i class="fas fa-question"></i>
                                </div>
                                <h2>Data Tidak Ditemukan</h2>
                                <p class="lead">
                                  Maaf kami tidak dapat menemukan data.
                                </p>
                            </div>
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
                <div class="float-right">
                  {{ $orders->links() }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

<form action="" method="POST" id="changeStatusForm">
    @csrf
    @method('PATCH')
    <input type="hidden" name="status" id="selectedStatus">
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script src="{{asset('/stisla-2.2.0/dist/assets/modules/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<script type="text/javascript">
  $('.daterange-cus').daterangepicker({
    locale: {format: 'DD/MM/YYYY'},
    drops: 'down',
    opens: 'left'
  });

</script>
<script type="text/javascript">
    $('.btn-status').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');
        var action = $(this).data('action');
        var message = "Status tidak dapat dikembalikan"

        $("#selectedStatus").val(action);
        if(action == '1') {
            var total = $(this).data('total');
            var limit = $(this).data('limit');
            message = "Sisa limit belanja Rp. " + limit + " . Total belanja " + total
        }

        swal({
          title: title + "?",
          text: message,
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((changeStatus) => {
          if (changeStatus) {
            $('#changeStatusForm').attr('action', href);
            $('#changeStatusForm').submit();
          }
        });
    });

    function submitForm()
    {
        console.log('change')
    }
    function report(){
        daterange = $('#daterange').val()
        search = $('#search').val()
        url = `{{url('orders')}}/report?daterange=${daterange}&search=${search}`
        window.location = url
    }
    </script>
@endsection

resources/views/admin/order/show.blade.php
@extends('layouts.admin')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('orders.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Detail Pesanan</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="{{ route('orders.index') }}">Pesanan</a></div>
          <div class="breadcrumb-item">Detail Pesanan</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                  <h4>Invoice : {{$order->invoice_code }}</h4>
                  <a class="btn btn-primary" href="{{ route('orders.export', $order) }}">Download PDF</a>
                </div>
                <div class="card-body">
                  <div class="row mb-2">
                    <div class="col-md-6">
                      <b>Nama Pegawai</b><br>
                      {{ $order->employee_name }}<br>
                    </div>
                    <div class="col-md-3">
                      <b>Total Harga</b><br>
                      {{ $order->total_harga }}
                    </div>
                    <div class="col-md-3">
                      <b>Status Pesanan</b><br>
                      {!! $order->label_status !!}<br><br>
                    </div>
                  </div>
                </div>
            </div>

            <div class="card">
              <div class="card-header">
                <h4>Data Produk</h4>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered">
                    <tr>
                      <th>No</th>
                      <th>Nama Produk</th>
                      <th>Harga</th>
                      <th>Qty</th>
                      <th>Sub Total</th>
                    </tr>
                    @php $no = 1 @endphp
                    @forelse ($order->details as $detail)
                        <tr >
                            <td>{{ $no }}</td>
                            <td>{{ $detail->product_name }}</td>
                            <td>{{ $detail->harga}}</td>
                            <td>{{ $detail->quantity}}</td>
                            <td>{{ $detail->sub_total_harga}}</td>
                        </tr>
                        @php $no++ @endphp
                    @empty
                    <tr>
                        <td colspan="5" align="center">
                            <div class="empty-state" data-height="400" style="height: 400px;">
                                <div class="empty-state-icon">
                                  <i class="fas fa-question"></i>
                                </div>
                                <h2>Data Tidak Ditemukan</h2>
                                <p class="lead">
                                  Maaf kami tidak dapat menemukan data.
                                </p>
                            </div>
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')

@endsection