routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/profile', 'ProfileController@edit')->name('profile');
    Route::put('/profile', 'ProfileController@update')->name('profile.update');
});

Route::group(
    ['middleware' => ['auth', 'role:administrator|admin|keuangan'], 'namespace' => 'Admin'],
    function () {
        Route::get('/', 'HomeController@index')->name('index');

        Route::resource('users', 'UserController');
        Route::resource('jabatans', 'JabatanController');

        Route::get('products/report', 'ProductController@report')->name('products.report');
        Route::resource('products', 'ProductController');

        Route::get('orders/report', 'OrderController@report')->name('orders.report');
        Route::get('/orders/export/{order}', 'OrderController@export')->name('orders.export');
        Route::resource('orders', 'OrderController')->only(['show', 'index']);
        Route::patch('/orders/{order}/change-status', 'OrderController@changeStatus')->name('orders.change-status');
    }
);

Route::group(
    ['middleware' => ['auth', 'role:user'], 'prefix' => 'app', 'as' => 'app.'],
    function () {
        Route::get('/', 'HomeController@index')->name('index');
        Route::get('product', 'ProductController@index')->name('product');
        Route::post('product/add-to-cart', 'ProductController@addToCart')->name('product.add-to-cart');
        Route::get('cart', 'ProductController@cart')->name('cart');
        Route::get('cart/remove-from-cart/{cart_id}', 'ProductController@removeFromCart')->name('cart.remove-from-cart');
        Route::post('cart/update-cart/{cart_id}', 'ProductController@updateCart')->name('cart.update-cart');

        Route::resource('orders', 'OrderController')->only(['show', 'index', 'store']);
        Route::get('/orders/export/{order}', 'OrderController@export')->name('orders.export');
    }
);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Storage;

class Product extends Model
{
    use SoftDeletes;

    protected $appends = ['photo_url', 'price_rupiah'];

    public function generateCode()
    {
        $this->code = "B" . str_pad($this->id, 5, '0', STR_PAD_LEFT);
        $this->save();
    }

    public function getPriceRupiahAttribute()
    {
        return 'Rp. ' . number_format($this->price, 0, ',', '.');
    }

    public function getPhotoUrlAttribute()
    {
        if ($this->photo) {
            return Storage::url($this->photo);
        }
        return asset('product.png');
    }
}

app/User.php
<?php

namespace App;

use App\Models\Jabatan;
use App\Models\Order;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Storage;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getPhotoUrlAttribute()
    {
        if ($this->photo) {
            return Storage::url($this->photo);
        }
        return Null;
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function jabatan()
    {
        return $this->belongsTo(Jabatan::class);
    }

    public function getLimitRemainingAdminAttribute()
    {
        $usage = $this->orders()
            ->whereBetween('status', [1, 3])
            ->where('created_at', ">=", now()->startOfMonth())
            ->withSum('details', 'sub_total_price')
            ->get()
            ->sum('details_sum_sub_total_price');
        return $this->limit_balance - $usage;
    }

    public function getLimitRemainingUserAttribute()
    {
        $usage = $this->orders()
            ->where('created_at', ">=", now()->startOfMonth())
            ->where('status', '<=', 4)
            ->withSum('details', 'sub_total_price')
            ->get()
            ->sum('details_sum_sub_total_price');
        return $this->limit_balance - $usage;
    }

    public function isUser()
    {
        return $this->role == 'user';
    }

    public function isAdmin()
    {
        return $this->role == 'admin';
    }

    public function isAdministrator()
    {
        return $this->role == 'administrator';
    }

    public function isKeuangan()
    {
        return $this->role == 'keuangan';
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Exports\StockProductReport;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Excel;
use Image;
use Storage;

class ProductController extends Controller
{
    public function index(Request $request)
    {
        $products = Product::latest();

        if ($request->has('search')) {
            $query = '%' . $request->search . '%';
            $products->where('name', 'LIKE', $query);
        }

        $products = $products->paginate(config('app.per_page'))->withQueryString();

        return view('admin.product.index', compact('products'));
    }

    public function create()
    {
        return view('admin.product.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|min:5',
            'price' => 'required|numeric',
            'stock' => 'required|numeric',
            'photo' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg',
        ], [], [
            'name' => 'nama produk',
            'price' => 'harga produk'
        ]);

        try {
            \DB::beginTransaction();
            $product = new Product;
            $product->name = $request->name;
            $product->price = $request->price;
            $product->stock = $request->stock;
            if (!is_null($request->photo)) {
                $file = $request->file('photo');
                $path = $file->hashName('photos');

                $image = Image::make($file);
                $image->fit(300, 300, function ($constraint) {
                    $constraint->aspectRatio();
                });
                Storage::put($path, (string) $image->encode());
                $product->photo = $path;
            }

            $product->save();
            $product->generateCode();

            \DB::commit();
        } catch (\Exception $e) {
            \DB::rollback();
            return redirect()->back()->withInput()->with('alert-error', 'Terjadi kesalahan server');
        }

        return redirect()->route('products.index')->with('alert-success', 'Berhasil Menambah Produk');
    }

    public function show(Product $product)
    {
        return view('admin.product.show', compact('product'));
    }

    public function edit(Product $product)
    {
        return view('admin.product.edit', compact('product'));
    }

    public function update(Request $request, Product $product)
    {
        $this->validate($request, [
            'name' => 'required|string|min:5',
            'price' => 'required|numeric',
            'stock' => 'required|numeric',
            'photo' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg',
        ], [], [
            'name' => 'nama produk',
            'price' => 'harga produk'
        ]);

        try {
            \DB::beginTransaction();
            $product->name = $request->name;
            $product->price = $request->price;
            $product->stock = $request->stock;
            if (!is_null($request->photo)) {
                $file = $request->file('photo');
                $path = $file->hashName('photos');

                $image = Image::make($file);
                $image->fit(300, 300, function ($constraint) {
                    $constraint->aspectRatio();
                });
                Storage::put($path, (string) $image->encode());
                $product->photo = $path;
            }

            $product->save();
            $product->generateCode();

            \DB::commit();
        } catch (\Exception $e) {
            dd($e);
            \DB::rollback();
            return redirect()->back()->withInput()->with('alert-error', 'Terjadi kesalahan server');
        }

        return redirect()->route('products.show', $product)->with('alert-success', 'Berhasil Mengubah Produk');
    }

    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('products.index')->with('alert-success', 'Berhasil menghapus produk');
    }

    public function report(Request $request)
    {
        $date = Carbon::now()->isoFormat('D MMMM Y');

        $products = Product::get();

        $filename = 'Laporan Stock Produk' . $date;

        return Excel::download(new StockProductReport($products, $filename), $filename . '.xlsx');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cart;
use Illuminate\Http\Request;
use App\Models\Product;
use Illuminate\Support\Facades\Auth;

class ProductController extends Controller
{
    public function index(Request $request)
    {
        $products = Product::paginate(12);

        return view('app.product', compact('products'));
    }

    public function addToCart(Request $request)
    {
        $product = Product::find($request->product_id);
        $user_id = Auth::id();

        $cart_product = Cart::where('user_id', $user_id)
            ->where('product_id', $product->id)
            ->first();

        if (is_null($cart_product)) {
            $cart_product = new Cart;
            $cart_product->user_id = $user_id;
            $cart_product->product_id = $product->id;
            $cart_product->quantity = 1;
            $cart_product->save();
        } else {
            $cart_product->increment('quantity');
        }

        return redirect()->back()->with('alert-success', 'Produk berhasil ditambahkan ke keranjang!');
    }

    public function removeFromCart(Request $request, $cart_id)
    {
        $user_id = Auth::id();

        $cart_product = Cart::where('user_id', $user_id)
            ->where('id', $cart_id)
            ->firstOrFail();

        $cart_product->delete();

        return redirect()->back()->with('alert-success', 'Produk berhasil dihapus dari keranjang!');
    }

    public function updateCart(Request $request, $cart_id)
    {
        $user_id = Auth::id();

        $cart_product = Cart::where('user_id', $user_id)
            ->where('id', $cart_id)
            ->firstOrFail();

        $cart_product->quantity = $request->quantity;
        $cart_product->save();

        return redirect()->back()->with('alert-success', 'Jumlah produk berhasil diperbarui!');
    }

    public function cart()
    {
        $user_id = Auth::id();

        $carts = Cart::where('user_id', $user_id)
            ->get();

        return view('app.cart', compact('carts'));
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.admin')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('products.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Tambah Produk</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Produk</a></div>
          <div class="breadcrumb-item">Tambah Produk</div>
        </div>
      </div>
      <form class="form" action="{{ route('products.store') }}" method="POST" id="form-product" enctype="multipart/form-data">
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data Produk Baru</h4>
              </div>
              <div class="card-body">
                @csrf
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">Nama Produk</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <input type="text" value="{{ old('name') }}" name="name" class="@error('name') is-invalid @enderror form-control">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">Harga</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <input type="number" min="1000" value="{{ old('price') }}" name="price" class="@error('price') is-invalid @enderror form-control">
                        @error('price')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">Stock</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <input type="number" min="0" value="{{ old('stock') }}" name="stock" class="@error('stock') is-invalid @enderror form-control">
                        @error('stock')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">Foto</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <div id="image-preview" class="image-preview">
                            <label for="image-upload" id="image-label">Choose File</label>
                            <input type="file" name="photo" id="image-upload" accept="image/*" />
                        </div>
                        @error('photo')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </form>
    </section>
  </div>
@endsection

@section('js')
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script>
    $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Pilih Foto",   // Default: Choose File
        label_selected: "Ganti Foto",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
    });
  </script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.admin')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('products.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Edit Produk</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Produk</a></div>
          <div class="breadcrumb-item">Edit Produk</div>
        </div>
      </div>
      <form class="form" action="{{ route('products.update', $product) }}" method="POST" id="form-product" enctype="multipart/form-data">
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Edit Produk: {{ $product->code }}</h4>
              </div>
              <div class="card-body">
                @csrf
                @method('PUT')
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">Nama Produk</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <input type="text" value="{{ old('name', $product->name) }}" name="name" class="@error('name') is-invalid @enderror form-control">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">Harga</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <input type="text" value="{{ old('price', $product->price) }}" name="price" class="@error('price') is-invalid @enderror form-control">
                        @error('price')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">Stock</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <input type="text" value="{{ old('stock', $product->stock) }}" name="stock" class="@error('stock') is-invalid @enderror form-control">
                        @error('stock')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">Foto</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <div id="image-preview" class="image-preview">
                            <label for="image-upload" id="image-label">Choose File</label>
                            <input type="file" name="photo" id="image-upload" accept="image/*" />
                        </div>
                        <span class="text-small text-info">*Kosongkan jika tidak ingin diubah</span>
                        @error('photo')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </form>
    </section>
  </div>
@endsection


@section('js')
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script>
    $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Pilih Foto",   // Default: Choose File
        label_selected: "Ganti Foto",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
    });
  </script>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.admin')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Produk</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Produk</a></div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Daftar Produk</h4>
              </div>
              <div class="card-body">
                <div class="float-left">
                    <a href="{{ route('products.create') }}" class="btn btn-primary">Tambah Produk</a>
                    <button onclick="report()" class="btn btn-info">Laporan Stok Produk</button>
                </div>
                <div class="float-right">
                  <form action="" method="GET">
                    <div class="input-group">
                      <input type="text" class="form-control" name="search" placeholder="Search" value="{{ request()->search }}">
                      <div class="input-group-append">
                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                      </div>
                    </div>
                  </form>
                </div>

                <div class="clearfix mb-3"></div>

                <div class="table-responsive">
                  <table class="table table-striped">
                    <tr>
                        <th>No</th>
                        <th>Foto</th>
                        <th>Kode Produk</th>
                        <th>Nama</th>
                        <th>Harga</th>
                        <th>Stock</th>
                        <th>#</th>
                    </tr>
                    @forelse ($products as $item)
                    <tr>
                        <td>{{ (($products->currentPage()-1) * $products->perPage()) + $loop->iteration }}</td>
                        <td><img src="{{ $item->photo_url }}" alt="" srcset="" style="height: 25px"></td>
                        <td>{{ $item->code }}</td>
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->price_rupiah }}</td>
                        <td>{{ $item->stock }}</td>
                        <td>
                            <a href="{{ route('products.show', $item) }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Lihat Produk"> <span class="fa fa-eye"></span></a>
                            <a href="{{ route('products.edit', $item) }}" class="btn btn-sm btn-warning" data-toggle="tooltip" data-placement="top" title="Edit Produk"> <span class="fa fa-edit"></span></a>
                            <span data-title="{{ $item->name }}" href="{{ route('products.destroy', $item) }}" class="btn btn-sm btn-danger btn-delete" data-toggle="tooltip" data-placement="top" title="Hapus Produk"> <span class="fa fa-trash"></span></span>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="6" align="center">
                            <div class="empty-state" data-height="400" style="height: 400px;">
                                <div class="empty-state-icon">
                                  <i class="fas fa-question"></i>
                                </div>
                                <h2>Data Tidak Ditemukan</h2>
                                <p class="lead">
                                  Maaf kami tidak dapat menemukan data.
                                </p>
                            </div>
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
                <div class="float-right">
                  {{ $products->links() }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')

<script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');
        swal({
          title: "Anda yakin akan menghapus Produk bernama "+ title +" ?",
          text: "Setelah dihapus data tidak dapat dikembalikan !",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        });
    });

    function report(){
        url = `{{url('products')}}/report`
        window.location = url
    }
    </script>
@endsection

resources/views/admin/product/show.blade.php
@extends('layouts.admin')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('products.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Detail Produk</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Produk</a></div>
          <div class="breadcrumb-item">Detail Produk</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data Produk</h4>
              </div>
              <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <center>
                        <img src="{{ $product->photo_url }}" class="img-fluid">
                        </center>
                    </div>
                    <div class="col-md-8">
                        <table class="table">
                            <tr>
                                <td>Nama</td>
                                <td>{{ $product->name }}</td>
                            </tr>
                            <tr>
                                <td>Kode Produk</td>
                                <td>{{ $product->code }}</td>
                            </tr>
                            <tr>
                                <td>Harga</td>
                                <td>{{ $product->price_rupiah }}</td>
                            </tr>
                            <tr>
                                <td>Stok</td>
                                <td>{{ $product->stock }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script>
    $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Pilih Foto",   // Default: Choose File
        label_selected: "Ganti Foto",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
    });
  </script>
@endsection