routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/profile', 'ProfileController@edit')->name('profile');
    Route::put('/profile', 'ProfileController@update')->name('profile.update');
});

Route::group(
    ['middleware' => ['auth', 'role:administrator|admin|keuangan'], 'namespace' => 'Admin'],
    function () {
        Route::get('/', 'HomeController@index')->name('index');

        Route::resource('users', 'UserController');
        Route::resource('jabatans', 'JabatanController');

        Route::get('products/report', 'ProductController@report')->name('products.report');
        Route::resource('products', 'ProductController');

        Route::get('orders/report', 'OrderController@report')->name('orders.report');
        Route::get('/orders/export/{order}', 'OrderController@export')->name('orders.export');
        Route::resource('orders', 'OrderController')->only(['show', 'index']);
        Route::patch('/orders/{order}/change-status', 'OrderController@changeStatus')->name('orders.change-status');
    }
);

Route::group(
    ['middleware' => ['auth', 'role:user'], 'prefix' => 'app', 'as' => 'app.'],
    function () {
        Route::get('/', 'HomeController@index')->name('index');
        Route::get('product', 'ProductController@index')->name('product');
        Route::post('product/add-to-cart', 'ProductController@addToCart')->name('product.add-to-cart');
        Route::get('cart', 'ProductController@cart')->name('cart');
        Route::get('cart/remove-from-cart/{cart_id}', 'ProductController@removeFromCart')->name('cart.remove-from-cart');
        Route::post('cart/update-cart/{cart_id}', 'ProductController@updateCart')->name('cart.update-cart');

        Route::resource('orders', 'OrderController')->only(['show', 'index', 'store']);
        Route::get('/orders/export/{order}', 'OrderController@export')->name('orders.export');
    }
);

app/User.php
<?php

namespace App;

use App\Models\Jabatan;
use App\Models\Order;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Storage;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getPhotoUrlAttribute()
    {
        if ($this->photo) {
            return Storage::url($this->photo);
        }
        return Null;
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function jabatan()
    {
        return $this->belongsTo(Jabatan::class);
    }

    public function getLimitRemainingAdminAttribute()
    {
        $usage = $this->orders()
            ->whereBetween('status', [1, 3])
            ->where('created_at', ">=", now()->startOfMonth())
            ->withSum('details', 'sub_total_price')
            ->get()
            ->sum('details_sum_sub_total_price');
        return $this->limit_balance - $usage;
    }

    public function getLimitRemainingUserAttribute()
    {
        $usage = $this->orders()
            ->where('created_at', ">=", now()->startOfMonth())
            ->where('status', '<=', 4)
            ->withSum('details', 'sub_total_price')
            ->get()
            ->sum('details_sum_sub_total_price');
        return $this->limit_balance - $usage;
    }

    public function isUser()
    {
        return $this->role == 'user';
    }

    public function isAdmin()
    {
        return $this->role == 'admin';
    }

    public function isAdministrator()
    {
        return $this->role == 'administrator';
    }

    public function isKeuangan()
    {
        return $this->role == 'keuangan';
    }
}

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>Koprasi Karyawan</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/modules/bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/modules/fontawesome/css/all.min.css') }}">

<!-- Plugins -->
<link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/modules/bootstrap-social/bootstrap-social.css') }}">
<link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/modules/select2/dist/css/select2.min.css') }}">

<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/css/style.min.css') }}">
<link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/css/components.css') }}">
<style>
    .select2{
        width: 100% !important;
    }

    table.table.form-table td {
        padding: 0 5px !important;
        height: 45px !important;
    }
</style>
@yield('css')
</head>

<body>
<div id="app">
    <div class="main-wrapper">
        @include('layouts.partials._navbar')
        @include('layouts.partials._sidebar')

        @yield('content')

        @include('layouts.partials._footer')
      </div>
</div>


<!-- General JS Scripts -->
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/jquery.min.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/popper.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/tooltip.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/nicescroll/jquery.nicescroll.min.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/moment.min.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/js/stisla.js') }}"></script>

<!-- Plugins -->
 <script src="{{ asset('/stisla-2.2.0/dist/assets/modules/sweetalert/sweetalert.min.js') }}"></script>
 <script src="{{ asset('/stisla-2.2.0/dist/assets/modules/select2/dist/js/select2.full.min.js') }}"></script>

<!-- Page Specific JS File -->

<!-- Template JS File -->
<script src="{{ asset('/stisla-2.2.0/dist/assets/js/scripts.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/js/custom.js') }}"></script>
<script type="text/javascript">
    @if(Session::has('alert-success'))
    swal("Success", "{{Session::get('alert-success')}}!", "success", {
      button: "Ok !",
    });
    @elseif(Session::has('alert-error'))
    swal("Error", "{{Session::get('alert-error')}}!", "error", {
      button: "Ok !",
    });
    @endif
</script>
@yield('js')
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Koprasi Karyawan</title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/modules/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/modules/fontawesome/css/all.min.css') }}">

  <!-- Plugins -->
  <link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/modules/bootstrap-social/bootstrap-social.css') }}">
  <link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/modules/select2/dist/css/select2.min.css') }}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/css/style.min.css') }}">
  <link rel="stylesheet" href="{{ asset('/stisla-2.2.0/dist/assets/css/components.css') }}">

<body class="layout-3">
  <div id="app">
    <div class="main-wrapper container">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <a href="{{ route('app.index') }}"><img src="{{ asset('logo.png') }}" class="navbar-brand sidebar-gone-hide" style="height: 50px;padding:2px"></a>
        <a href="#" class="nav-link sidebar-gone-show" data-toggle="sidebar"><i class="fas fa-bars"></i></a>
        <form class="form-inline ml-auto">
          <ul class="navbar-nav">
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
          </ul>
        </form>
        <ul class="navbar-nav navbar-right">
          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg {{ count($carts) ? 'beep' : '' }}"><i class="fas fa-shopping-cart"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Keranjng Belanja
              </div>
              <div class="dropdown-list-content dropdown-list-icons">
              @foreach ($carts as $item)
                    <a href="#" class="dropdown-item dropdown-item-unread">
                        <div class="dropdown-item-icon">
                            <img src="{{ $item->product->photo_url }}" alt="" style="width: -webkit-fill-available">
                        </div>
                        <div class="dropdown-item-desc">
                            {{ $item->product->name }}
                            <div class="time text-primary">{{ $item->quantity }} x {{ $item->product->price_rupiah }}</div>
                        </div>
                    </a>
                @endforeach
                </div>
              <div class="dropdown-footer text-center">
                <a href="{{ route('app.cart') }}">Checkout <i class="fas fa-chevron-right"></i></a>
              </div>
            </div>
          </li>
          <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="{{ \Auth::user()->photoUrl ?? asset('stisla-2.2.0/dist/assets/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">Hi, {{ request()->user()->name }}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
            {{-- <div class="dropdown-title">Logged in 5 min ago</div> --}}

            <a href="{{ route('profile') }}" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Setting Profile
            </a>
            {{--
            <a href="features-activities.html" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Activities
            </a>
            <a href="features-settings.html" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Settings
            </a> --}}
            {{-- <div class="dropdown-divider"></div> --}}
                <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Logout
            </a>
            </div>
        </li>
        </ul>
      </nav>

      <nav class="navbar navbar-secondary navbar-expand-lg">
        <div class="container">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a href="{{ route('app.index') }}" class="nav-link"><i class="fa fa-home"></i><span>Home</span></a>
            </li>
            <li class="nav-item">
              <a href="{{ route('app.orders.index') }}" class="nav-link"><i class="fa fa-shopping-cart"></i><span>Riwayat Pesanan</span></a>
            </li>
            <li class="nav-item">
              <a href="{{ route('app.product') }}" class="nav-link"><i class="fa fa-box"></i><span>Produk</span></a>
            </li>
          </ul>
        </div>
      </nav>

      <!-- Main Content -->
      <div class="main-wrapper">
          <div class="section-body">
            @yield('content')
          </div>
        </section>
      </div>
      @include('layouts.partials._footer')
    </div>
  </div>


<!-- General JS Scripts -->
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/jquery.min.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/popper.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/tooltip.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/nicescroll/jquery.nicescroll.min.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/moment.min.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/js/stisla.js') }}"></script>

<!-- Plugins -->
 <script src="{{ asset('/stisla-2.2.0/dist/assets/modules/sweetalert/sweetalert.min.js') }}"></script>
 <script src="{{ asset('/stisla-2.2.0/dist/assets/modules/select2/dist/js/select2.full.min.js') }}"></script>

<!-- Page Specific JS File -->

<!-- Template JS File -->
<script src="{{ asset('/stisla-2.2.0/dist/assets/js/scripts.js') }}"></script>
<script src="{{ asset('/stisla-2.2.0/dist/assets/js/custom.js') }}"></script>
<script type="text/javascript">
    @if(Session::has('alert-success'))
    swal("Success", "{{Session::get('alert-success')}}!", "success", {
      button: "Ok !",
    });
    @elseif(Session::has('alert-error'))
    swal("Error", "{{Session::get('alert-error')}}!", "error", {
      button: "Ok !",
    });
    @endif
</script>
@yield('js')
</body>
</html>